import { api } from './api.js'

export function createStorytellerService(password) {
  const command = (path, body) => api(path, {
    method: 'POST',
    headers: { 'X-Storyteller-Password': password },
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
  })

  return {
    configure: (script, playerCount) => command('/api/config', {
      script,
      player_count: playerCount,
    }),
    assignRandom: () => command('/api/assign'),
    assignManual: (draft) => command('/api/assign/manual', draft),
    setSentinel: (value) => command('/api/sentinel', { value }),
    toggleFabled: (id, on) => command('/api/fabled', { id, on }),
    start: () => command('/api/start'),
    navigate: (payload) => command('/api/night/step', payload),
    selectNightTargets: (payload) => command('/api/night/select', payload),
    resolveOutcome: (payload) => command('/api/night/outcome', payload),
    deliverInformation: (payload) => command('/api/night/information', payload),
    applyNightEffect: (payload) => command('/api/night/effect', payload),
    confirmPitHag: (payload) => command('/api/night/pit-hag', payload),
    undoNightEvent: (payload) => command('/api/night/undo', payload),
    setDayStage: (stage) => command('/api/day/stage', { stage }),
    startNomination: (nominator, nominee) => command('/api/nomination', { nominator, nominee }),
    toggleVote: (seat) => command('/api/nomination/vote', { seat }),
    resolveNomination: (passed) => command('/api/nomination/resolve', { passed }),
    endDay: () => command('/api/day/end'),
    addTraveler: (name) => command('/api/traveler/add', { name }),
    assignTraveler: (id, role, align) => command('/api/traveler/assign', { id, role, align }),
    setTravelerExile: (id, exiled) => command('/api/traveler/exile', { id, exiled }),
    toggleTravelerAlive: (id) => command('/api/traveler/alive', { id }),
    answerChatInvite: (id, accept) => command(`/api/chat-st/${id}/invite`, { accept }),
    sendStorytellerChat: (id, text) => command(`/api/chat-st/${id}/send`, { text }),
    leaveStorytellerChat: (id) => command(`/api/chat-st/${id}/leave`),
    closeStorytellerChat: (id) => command(`/api/chat-st/${id}/close`),
    recallChats: () => command('/api/chat-st/recall'),
    setRoom: (code) => command('/api/room', { code }),
    setFake: (payload) => command('/api/fake', payload),
    setMarker: (payload) => command('/api/marker', payload),
    setRedHerring: (seat) => command('/api/fortuneteller/red', { seat }),
    toggleSeatAlive: (seat) => command(`/api/seat/${seat}/alive`),
    togglePlayerAlive: (playerId) => command(`/api/player/${playerId}/alive`),
    removePlayer: (playerId) => command(`/api/player/${playerId}/remove`),
    issueRecoveryCode: (playerId) => command(`/api/st/players/${playerId}/recovery-code`),
    revokeGuestSessions: (playerId) => command(`/api/st/players/${playerId}/revoke-guest-sessions`),
    loadSave: () => command('/api/load'),
    resetGame: () => command('/api/reset'),
    setWinner: (winner) => command('/api/end', { winner }),
    markReview: (seat, night, wrong) => command('/api/review/mark', { seat, night, wrong }),
  }
}
